site_name: Portfolio Tomasz Mirkowski

site_name: Moje projekty
site_author: Tomasz Mirkowski
site_description: >-
    Portfolio moich projektów.

repo_name: tomalom76/portfolio
repo_url: https://github.com/tomalom76/portfolio

theme:
  name: material
  palette:
    primary: blue

nav:
- Strona Domowa: index.md
- Obecny projekt:
  - "Predykcja cen i stanów mieszkań": Investoro/index.md
- Poprzednie projekty:
  - "Stan"   : Stan/index.md  
  - "MójGPT" : mojGPT/index.md
  - "Grupy"  : grupy/index.md
  - "Titanic": Titanic/index.md
  - "Iris"   : Iris/index.md
  - "Thermal": Thermal/index.md

markdown_extensions:
  - attr_list
  - md_in_html

plugins:
  - glightbox