site_name: Portfolio Tomasz Mirkowski

site_name: Moje projekty
site_author: Tomasz Mirkowski
site_description: >-
    Portfolio TOMASZ MIRKOWSKI moje projekty.

repo_name: tomalom76/portfolio
repo_url: https://github.com/tomalom76/portfolio

theme:
  name: material
  palette:
    primary: blue

nav:
- Home: index.md
- Obecny projekt:
  - "Projekt przenoszenia domen ZUS z Itanium na x86": Assecco/index.md
  
- Poprzednie projekty:
  - "Projekty Agentów AI - lista projektów związanych z kursem": Agenci/index.md
  - "Predykcja cen i stanów mieszkań ETAP III": Investoro3/index.md
  - "Investoro - ETAP II" : Investoro/index.md
  - "Investoro - ETAP I": Investoro2/index.md
  - "Stan"   : Stan/index.md  
  - "MójGPT" : mojGPT/index.md
  - "Faktury": Faktury-invoice/index.md
  - "Grupy"  : grupy/index.md
  - "Titanic": Titanic/index.md
  - "Iris"   : Iris/index.md
  - "Thermal": Thermal/index.md

- Konferencje:
  - "III Konferencja DATA SCIENTIST 27 czerwca 2026": Konferencja3/index.md
  - "II Konferencja DATA SCIENCE 29 listopada 2025": Konferencja2/index.md

markdown_extensions:
  - attr_list
  - md_in_html

plugins:
  - glightbox